version: '3'
services:
  centos:
    image: pycontribs/centos:7
    container_name: centos
    entrypoint: "sleep infinity"
  
  ubuntu:
    image: pycontribs/ubuntu:latest
    container_name: ubuntu
    entrypoint: "sleep infinity"